CREATE TABLE levels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(16) NOT NULL UNIQUE,
    display_name VARCHAR(64) NOT NULL,
    difficulty_weight INT NOT NULL,
    description VARCHAR(255)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    total_score INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE puzzles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    level_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_puzzles_level FOREIGN KEY (level_id) REFERENCES levels(id)
);

CREATE TABLE puzzle_constraints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    puzzle_id BIGINT NOT NULL UNIQUE,
    circle_sum_1 SMALLINT NOT NULL,
    circle_sum_2 SMALLINT NOT NULL,
    circle_sum_3 SMALLINT NOT NULL,
    circle_sum_4 SMALLINT NOT NULL,
    color_zone_map CLOB NOT NULL,
    circle_cell_map CLOB NOT NULL,
    CONSTRAINT fk_constraints_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(id)
);

CREATE TABLE save_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    puzzle_id BIGINT NOT NULL,
    level_id BIGINT NOT NULL,
    grid_state VARCHAR(32) NOT NULL,
    elapsed_seconds INT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    saved_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_save_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_save_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(id),
    CONSTRAINT fk_save_level FOREIGN KEY (level_id) REFERENCES levels(id)
);

CREATE TABLE game_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    puzzle_id BIGINT NOT NULL,
    level_id BIGINT NOT NULL,
    final_grid_state VARCHAR(32) NOT NULL,
    completion_seconds INT NOT NULL,
    score_earned INT NOT NULL,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attempt_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_attempt_puzzle FOREIGN KEY (puzzle_id) REFERENCES puzzles(id),
    CONSTRAINT fk_attempt_level FOREIGN KEY (level_id) REFERENCES levels(id)
);

CREATE INDEX idx_save_user_completed ON save_games(user_id, is_completed);
CREATE INDEX idx_attempt_user_completed_at ON game_attempts(user_id, completed_at);

INSERT INTO levels (code, display_name, difficulty_weight, description) VALUES
('EASY', 'Easy', 1, 'Niveau facile'),
('MEDIUM', 'Medium', 2, 'Niveau intermédiaire'),
('HARD', 'Hard', 3, 'Niveau difficile');

INSERT INTO puzzles (level_id, name, status) VALUES
((SELECT id FROM levels WHERE code = 'EASY'), 'Puzzle Easy #1', 'ACTIVE'),
((SELECT id FROM levels WHERE code = 'MEDIUM'), 'Puzzle Medium #1', 'ACTIVE'),
((SELECT id FROM levels WHERE code = 'HARD'), 'Puzzle Hard #1', 'ACTIVE');

INSERT INTO puzzle_constraints (puzzle_id, circle_sum_1, circle_sum_2, circle_sum_3, circle_sum_4, color_zone_map, circle_cell_map) VALUES
((SELECT id FROM puzzles WHERE name = 'Puzzle Easy #1'),
 10, 14, 18, 20,
 '{"RED":[0,1,3],"BLUE":[2,5],"GREEN":[4,7,8],"YELLOW":[6]}',
 '{"C1":[0,1,3,4],"C2":[1,2,4,5],"C3":[3,4,6,7],"C4":[4,5,7,8]}'
),
((SELECT id FROM puzzles WHERE name = 'Puzzle Medium #1'),
 12, 17, 16, 19,
 '{"RED":[0,2,3],"BLUE":[1,4],"GREEN":[5,7,8],"YELLOW":[6]}',
 '{"C1":[0,1,3,4],"C2":[1,2,4,5],"C3":[3,4,6,7],"C4":[4,5,7,8]}'
),
((SELECT id FROM puzzles WHERE name = 'Puzzle Hard #1'),
 15, 15, 15, 15,
 '{"RED":[0,4,8],"BLUE":[1,2,3],"GREEN":[5,6,7]}',
 '{"C1":[0,1,3,4],"C2":[1,2,4,5],"C3":[3,4,6,7],"C4":[4,5,7,8]}'
);
